### ISSUE TITLE
files with a byte size larger than an int cause i/o errors

### ISSUE THREAD

**Issue by anotherMuppet** [rdiff-backup/rdiff-backup-fs#2]
from the original google code page below:

Posted on Apr 13, 2011 by Happy Bear
When listing large files (over 4GB) which have been archived with rdiffbackup, an incorrect filesize is reported by rdiff-backup-fs - smaller than the real filesize. (It was 1.9GB in my test).

I tried this on Ubuntu 10.10, 32 bit.

I know there was a fix changing the integer used to hold the filesize to long long, but it still does not seem to work. Maybe it does work on a 64 bit operating system?

Otherwise rdiff-backup-fs is great, thanks to the developer!

Comment #1
Posted on Apr 13, 2011 by Happy Rhino
Yes, that was a very quick fix in hope, that it would be enough. Obviously it wasn't, so I'll try to provide a better fix this time. I am closing the issue on archfs web page too.

**Comment by ericzolf** [comment]
Beware that nobody is actively maintaining the code base. We're just keeping a copy until someone volunteers.

**Comment by anotherMuppet** [comment]
i've left a [$30 bounty](https://www.bountysource.com/issues/96838952-files-with-a-byte-size-larger-than-an-int-cause-i-o-errors) as an incentive for someone to resume maintenance
